### ISSUE TITLE
Integration with WP default gallery

### ISSUE THREAD

**Issue by hafizovic** [ademilter/bricklayer#11]
Hello, i really dont know is this issue...
i'm trying to integrate bricklayer with default WP gallery, i include all the stuff, and in developer tools i can see  appended stuff,
but columns are 100% width

DEMO: http://hafizovic.ba/wp/246-2/

This is link to file where i initialized script
http://hafizovic.ba/wp/wp-content/themes/hafizovic/js/custom.js?ver=05012016

**Comment by f** [comment]
@hafizovic Do you include CSS?

**Comment by hafizovic** [comment]
Yeah, this one
http://hafizovic.ba/wp/wp-content/themes/hafizovic/css/bricklayer.min.css?ver=0.4.2

**Comment by f** [comment]
Does the container have `bricklayer` class name? It seems you do not.
