### ISSUE TITLE
ES6/2015 support

### ISSUE THREAD

**Issue by nlemoine** [ademilter/bricklayer#18]
Hi! 

I tried to use bricklayer in my ES6/babelified code and the import seems to fail:

``` javascript
import Bricklayer from 'bricklayer'
```

The `Bricklayer` results in an empty object.

**Comment by f** [comment]
Did you check out this: http://www.webpackbin.com/V1L4KdVeW

**Comment by blackfyre** [comment]
I also get `Uncaught TypeError: Bricklayer is not a constructor`/empty object errors even with the original npm example...

This is my whole js file:

```javascript
window.$ = window.jQuery = require('jquery');
require('bootstrap-sass');

let Bricklayer = require("bricklayer");

let bricks = new Bricklayer(document.querySelector('.bricklayer'));
```

**Comment by nlemoine** [comment]
I forgot to mention that i'm also using Browserify to bundle my js.

**Comment by doup** [comment]
I've the same problem as @blackfyre, I've tried loading both the node and regular versions found in the `dist` folder.

**Comment by AlonsoK28** [comment]
There are solution fo this?
