### ISSUE TITLE
bricklayer.destroy()

### ISSUE THREAD

**Issue by shohagbhuiyan** [ademilter/bricklayer#32]
Trying to use Bricklayer.js in multiple IDs in same page. Or even it will be helpful to know, how to bricklayer all `.bricklayer` classes.

Any proper way to use bricklayer.destroy(); ? Is there any good example?

I tried:
`bricklayer.destroy();`
`var bricklayer = new Bricklayer(document.getElementById('bricklayer'));`

The code throws error `Uncaught TypeError: Cannot read property 'destroy' of undefined`

**Comment by evoactivity** [comment]
Multiple id's on the same page would be straight up wrong, you should use classes if there are multiple of them on the page.

you can't call `bricklayer.destroy()` before you've created your bricklayer instance
