### ISSUE TITLE
AngularJS Module

### ISSUE THREAD

**Issue by JohnnyTheTank** [ademilter/bricklayer#9]
Hello Guys,
I've created a angular module for bricklayer: https://github.com/JohnnyTheTank/angular-bricklayer
Any wishes?

**Comment by f** [comment]
Woohoo! This is awesome! 👍

**Comment by f** [comment]
@JohnnyTheTank We'll add it to the README file so people can reach out :)

**Comment by JohnnyTheTank** [comment]
@f thats great, thank you :)

**Comment by JohnnyTheTank** [comment]
I need a "redraw" method. is there any possibilty for this?

**Comment by f** [comment]
@JohnnyTheTank 
This will redraw elements:
```
bricklayer.reorderElements(bricklayer.columnCount)
```

**Comment by JohnnyTheTank** [comment]
@f thank you, but this is not exactly what I need. I need a refresh method that just resizes the items, but doesn't make a new order. is this possible?

**Comment by JohnnyTheTank** [comment]
@f ah, everything is right! it works for me!

**Comment by JohnnyTheTank** [comment]
Added redraw support after images get loaded: http://plnkr.co/edit/mo3G36

**Comment by f** [comment]
@JohnnyTheTank Now we have `redraw` and `destroy` methods! Please check out README.

**Comment by JohnnyTheTank** [comment]
@f thats great!

**Comment by JohnnyTheTank** [comment]
@f is there any logic available to redraw the grid after the images get loaded?

I'm going to implement a image loader detection, and trigger the redraw method after images get loaded, but it would be better if bricklayer offers this possibilty by itself

**Comment by f** [comment]
@JohnnyTheTank We try to keep Bricklayer as simple as possible. Otherwise it will get fat which we don't want. I think it should be seperated. BTW, have you tried desandro's imagesLoaded extension?

**Comment by JohnnyTheTank** [comment]
@f thank you for your answer. I will probably use desandro's imagesLoaded extension.

**Comment by JohnnyTheTank** [comment]
@f I added imagesLoaded support in v1.1.0 http://plnkr.co/edit/mo3G36

**Comment by f** [comment]
@JohnnyTheTank Should we close this issue?

**Comment by JohnnyTheTank** [comment]
yes
